# Generated by Django 4.0.4 on 2022-06-02 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('age', models.IntegerField(blank=True, verbose_name='age')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('company', models.CharField(blank=True, max_length=60, verbose_name='company')),
                ('type_of_activity', models.CharField(blank=True, max_length=70, verbose_name='type of activity')),
                ('type_of_blog', models.CharField(blank=True, max_length=50, verbose_name='type of blog')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Writer',
                'verbose_name_plural': 'Writers',
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last_name')),
                ('age', models.IntegerField(blank=True, verbose_name='age')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reader',
                'verbose_name_plural': 'Readers',
            },
        ),
    ]
