# Generated by Django 4.0.4 on 2022-06-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_writer_type_of_activity_writer_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='type_of_blog',
        ),
        migrations.AddField(
            model_name='writer',
            name='blog',
            field=models.CharField(blank=True, max_length=50, verbose_name='blog'),
        ),
    ]
