# Generated by Django 4.0.4 on 2022-06-10 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_readerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.reader'),
        ),
    ]
