# Generated by Django 4.0.4 on 2022-06-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_readerprofile_profile_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activity',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
