# Generated by Django 4.0.4 on 2022-06-19 12:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0014_alter_post_author'),
        ('users', '0011_alter_follow_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Writer',
            new_name='Author',
        ),
    ]
