# Generated by Django 4.0.4 on 2022-06-19 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_category_post_is_draft_post_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
