# Generated by Django 4.0.5 on 2022-06-26 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
